# Generated by Django 4.2.4 on 2023-12-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='order',
        ),
    ]
