# Generated by Django 4.2.4 on 2023-12-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_playlisttrack_options_playlisttrack_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
